name: Lint and Check Unused Code

on:
  push:
    branches:
      - main
      - "feature/*" # or any other branches you want to monitor
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4" # specify your desired Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 vulture  # install Flake8 and Vulture

      # Step 4: Run Flake8 to lint the code
      - name: Run Flake8
        run: flake8 .

      # Step 5: Run Vulture to check for unused code
      - name: Run Vulture to find unused code
        run: vulture . --min-confidence 80 # You can adjust confidence threshold


      # Optionally, add a step to fail if the vulture or flake8 steps fail
